name: hello-snap-test # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'

grade: stable # must be 'stable' to release into candidate/stable channels

apps:
  hello:
    command: hello

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
